### ISSUE TITLE
RE: Error E39: Memory size has to be aligned to guest page size

### ISSUE THREAD

**Issue by godveryday** [renode/renode#712] opened 2024-11-28 07:05 UTC
I created and ran a repl file based on leon3, but the following error occurred:

error e39: exception was thrown during registratin of 'cpu' in 'sysbus' memory size has to be aligned to guest page size

I want to know the cause of why this error occurs.
I'll show you my entire code, so can you tell me the solution and the cause?

sysbus:
	Endianess: Endianess.BigEndian

rom: Memory.MappedMemory @ sysbus 0x00000000
	size: 0x80000

edac: Memory.MappedMemroy @ sysbus 0x40000000
	size: 0x400000

io_area: Memory.MappedMemory @ sysbus 0x20000000
	size: 0x218

reg: Memory.MappedMemory @ sysbus 0x20000220
	size: 0x14

gp_reg: Memory.MappedMemory @ sysbus 0x20000240
	size: 0xC

... 

uart0: UART.GaislerAPBUART @ sysbus <0x80000100, +0x100>

cpu: CPU.Sparc @ sysbus
	cpuType: "leon3"

**Comment by PiotrZierhoffer** [comment] 2024-11-28 11:04
This is duplicate of #709, closing

**Closed by PiotrZierhoffer** 2024-11-28 11:04 UTC
