### ISSUE TITLE
Unable to use network interface on beaglev_startlight example

### ISSUE THREAD

**Issue by sand7000** [renode/renode#496] opened 2023-08-11 02:17 UTC
### Description

Beaglev_starlight example boots but network interface cannot be brought up.

### Expected behaviour

What you expected to happen, and what is happening instead.

### How to reproduce?

In terminal run:

```
cd renode_1.13.3_portable/
sudo ./renode
```

In Renode run:

```
emulation CreateTap "tap0" "tap"
emulation CreateSwitch "switch1"
connector Connect host.tap switch1
start @scripts/single-node/beaglev_starlight.resc
connector Connect sysbus.ethernet switch1
```

The tap device is created on the host as expected. In the terminal I see:

```
20:45:35.8887 [WARNING] ethernet: Access to unknown phy 0 (3)
20:45:36.0611 [WARNING] ethernet: Access to unknown phy 1 (2)
20:45:36.0991 [WARNING] ethernet: Access to unknown phy 2 (2)
20:45:36.1328 [WARNING] ethernet: Access to unknown phy 3 (2)
20:45:36.1618 [WARNING] ethernet: Access to unknown phy 4 (2)
20:45:36.1974 [WARNING] ethernet: Access to unknown phy 5 (2)
20:45:36.2254 [WARNING] ethernet: Access to unknown phy 6 (2)
20:45:36.2833 [WARNING] ethernet: Access to unknown phy 8 (2)
20:45:36.3124 [WARNING] ethernet: Access to unknown phy 9 (2)
20:45:36.3404 [WARNING] ethernet: Access to unknown phy 10 (2)
20:45:36.3697 [WARNING] ethernet: Access to unknown phy 11 (2)
20:45:36.3994 [WARNING] ethernet: Access to unknown phy 12 (2)
20:45:36.4289 [WARNING] ethernet: Access to unknown phy 13 (2)
20:45:36.4610 [WARNING] ethernet: Access to unknown phy 14 (2)
20:45:36.4972 [WARNING] ethernet: Access to unknown phy 15 (2)
20:45:36.5269 [WARNING] ethernet: Access to unknown phy 16 (2)
20:45:36.5559 [WARNING] ethernet: Access to unknown phy 17 (2)
20:45:36.5996 [WARNING] ethernet: Access to unknown phy 18 (2)
20:45:36.6456 [WARNING] ethernet: Access to unknown phy 19 (2)
20:45:36.6737 [WARNING] ethernet: Access to unknown phy 20 (2)
20:45:36.7034 [WARNING] ethernet: Access to unknown phy 21 (2)
20:45:36.7317 [WARNING] ethernet: Access to unknown phy 22 (2)
20:45:36.7626 [WARNING] ethernet: Access to unknown phy 23 (2)
20:45:36.7912 [WARNING] ethernet: Access to unknown phy 24 (2)
20:45:36.8207 [WARNING] ethernet: Access to unknown phy 25 (2)
20:45:36.8495 [WARNING] ethernet: Access to unknown phy 26 (2)
20:45:36.8792 [WARNING] ethernet: Access to unknown phy 27 (2)
20:45:36.9074 [WARNING] ethernet: Access to unknown phy 28 (2)
20:45:36.9353 [WARNING] ethernet: Access to unknown phy 29 (2)
20:45:36.9639 [WARNING] ethernet: Access to unknown phy 30 (2)
20:45:36.9920 [WARNING] ethernet: Access to unknown phy 31 (2)
20:46:01.9569 [WARNING] ethernet: Access to unknown phy 0 (4)
20:48:24.2422 [INFO] switch1: Interface 00:00:DE:AD:BE:EF attached
20:51:50.5751 [WARNING] ethernet: Access to unknown phy 0 (4)
```

In the UART window I can login to linux and try to bring up the interface:

```
# ip link set eth0 up
[  131.978544] stmmaceth 10020000.gmac eth0: validation of rgmii-txid with support 
0000000,00000000,00006280 and advertisement 0000000,00000000,00006280 failed: -22
[  131.978978] stmmaceth 10020000.gmac eth0: stmmac_open: Cannot attach to PHY (err
or: -22)
ip: SIOCSIFFLAGS: Invalid argument
```

### Environment

Please, provide the following information:

- OS: Archlinux fully updated
- Renode version: https://github.com/renode/renode/releases/download/v1.13.3/renode-1.13.3.linux-portable.tar.gz

### Do you plan to address this issue and file a PR?

Support appreciated!

**Comment by PiotrZierhoffer** [comment] 2023-09-21 10:57
This is effectively a duplicate of #222 

We were looking into this recently, we have the fix for phy, but the communication itself doesn't work yet. We'll continue this in the original ticket

**Closed by PiotrZierhoffer** 2023-09-21 10:57 UTC
